# build.yml
# Purpose: Build via github actions
# Author(s): Vincent392

name: Build with gcc

on:
  push:
    paths:
      - '**/**.cpp'
      - '**/**.hpp'
      - '**/**.c'
      - '**/**.h'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '**/**.cpp'
      - '**/**.hpp'
      - '**/**.c'
      - '**/**.h'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with g++
        run: |
           cd src
           g++ tdpm_main.cpp -o tdpm
           g++ tdpm_pkg_main.cpp -shared -o tdpm-pkg.so
           cd ..
      - name: Move to artifact directory
        run: |
          mkdir -p artifact/bin
          cd src
          mv tdpm ../artifact/
          mv *.so ../artifact/bin/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TDPM-Linux
          path: artifact/

  build-mac-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build with g++
        run: |
           cd src
           g++ tdpm_main.cpp -o tdpm-intel.app
           g++ tdpm_pkg_main.cpp -shared -o tdpm-pkg-intel.dylib
           cd ..
      - name: Move to artifact directory
        run: |
          mkdir -p artifact/bin
          cd src
          mv tdpm-intel.dylib ../artifact/
          mv *.dylib ../artifact/bin/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TDPM-macOS-Intel
          path: artifact/

   build-mac-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with g++
        run: |
           cd src
           g++ tdpm_main.cpp -o tdpm.app
           g++ tdpm_pkg_main.cpp -shared -o tdpm-pkg.dylib
           cd ..
      - name: Move to artifact directory
        run: |
          mkdir -p artifact/bin
          cd src
          mv tdpm-intel.dylib ../artifact/
          mv *.dylib ../artifact/bin/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TDPM-macOS-ARM
          path: artifact/
